#include <iostream>

/**
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

unsigned long fibEvenSum(long long max){
	unsigned long sum = 0;
	unsigned long prev = 0;
	unsigned long curr = 1;

	while(curr < 4000000){		
		if( (curr % 2) == 0 ){
			sum += curr;
		}

		unsigned long tmp = prev;
		prev = curr;
		curr += tmp;
	}
	
	return sum;
}


int main(){
	std::cout << fibEvenSum(4000000) << std::endl;	
}
